import { FAQItem } from "@/types/faq";

export const KANNADA_FAQ: FAQItem[] = [
  {
    question: "What is Kannada typing using English letters?",
    answer:
      "Kannada typing using English letters means writing Kannada words phonetically in English and converting them into the Kannada script. For example, typing 'namaskara' converts to 'ನಮಸ್ಕಾರ'.",
  },
  {
    question: "Which script does the Kannada typing tool use?",
    answer:
      "TypeBharat's Kannada typing tool uses the Kannada (ಕನ್ನಡ) script, the standard writing system used for the Kannada language.",
  },
  {
    question: "Do I need to learn the Kannada keyboard layout?",
    answer:
      "No. You don't need to learn a Kannada keyboard layout. Simply type Kannada words using English letters and the tool converts them automatically into the Kannada script.",
  },
  {
    question: "Is the Kannada typing tool free?",
    answer:
      "Yes. TypeBharat's Kannada typing tool is completely free with no sign-up, subscription, or usage limits.",
  },
  {
    question: "Can I paste English text and convert it to Kannada?",
    answer:
      "Yes. You can paste English text written phonetically and instantly convert it into Kannada script.",
  },
  {
    question: "Is this a Kannada translation tool?",
    answer:
      "No. This is a transliteration tool, not a translation tool. It converts English phonetic input into Kannada script while preserving pronunciation and meaning.",
  },
  {
    question: "How accurate is the English to Kannada transliteration?",
    answer:
      "The transliteration is highly accurate for common Kannada words and phrases. When multiple spellings are possible, TypeBharat provides suggestions so you can choose the correct one.",
  },
  {
    question: "Does TypeBharat save my Kannada text?",
    answer:
      "No. Everything you type stays in your browser. TypeBharat does not store, track, or log your text.",
  },
  {
    question: "Can I use this Kannada typing tool for professional or commercial work?",
    answer:
      "Yes. The Kannada text generated by TypeBharat can be used for personal, educational, business, and commercial purposes.",
  },
  {
    question: "Can I type long paragraphs, articles, or documents in Kannada?",
    answer:
      "Yes. TypeBharat supports writing long paragraphs, articles, emails, assignments, and documents in Kannada without restrictions.",
  },
];

export const LEARN_KANNADA_FAQ: FAQItem[] = [
  {
    question: "What script is used to write Kannada?",
    answer:
      "Kannada is written using the Kannada script, a Brahmic writing system that has evolved over many centuries and is used primarily in the Indian state of Karnataka.",
  },
  {
    question: "How many vowels are there in Kannada?",
    answer:
      "Kannada has 16 independent vowels. These vowels combine with consonants using vowel signs (matras) to form complete syllables.",
  },
  {
    question: "How many consonants are there in Kannada?",
    answer:
      "Kannada has 34 primary consonants along with additional conjunct forms and Sanskrit-derived characters used in traditional writing.",
  },
  {
    question: "Why do Kannada letters look rounded?",
    answer:
      "The Kannada script developed from writing on palm leaves, where rounded strokes helped prevent the leaves from tearing. This gives Kannada its distinctive curved appearance.",
  },
  {
    question: "What are Kannada vowel signs (matras)?",
    answer:
      "Kannada vowel signs are marks attached to consonants to change their vowel sound. They are an essential part of reading and writing Kannada correctly.",
  },
  {
    question: "Is Kannada written from left to right?",
    answer:
      "Yes. Kannada is written from left to right. Each consonant has an inherent vowel unless modified by a vowel sign or the virama (್).",
  },
  {
    question: "Where is Kannada spoken?",
    answer:
      "Kannada is primarily spoken in the Indian state of Karnataka. It is also spoken by Kannada-speaking communities across India and around the world.",
  },
  {
    question: "Why is Kannada considered a Classical Language of India?",
    answer:
      "Kannada has a rich literary history spanning more than a thousand years. Its extensive body of classical literature and historical inscriptions led to its recognition as a Classical Language of India.",
  },
];