import { FAQItem } from "@/types/faq";

export const TELUGU_FAQ: FAQItem[] = [
  {
    question: "What is Telugu typing using English letters?",
    answer:
      "Telugu typing using English letters means writing Telugu words phonetically in English and converting them into the Telugu script. For example, typing 'namaskaram' converts to 'నమస్కారం'.",
  },
  {
    question: "Which script does the Telugu typing tool use?",
    answer:
      "TypeIndian's Telugu typing tool uses the Telugu (తెలుగు) script, the standard writing system used for the Telugu language.",
  },
  {
    question: "Do I need to learn the Telugu keyboard layout?",
    answer:
      "No. You don't need to learn a Telugu keyboard layout. Simply type Telugu words using English letters and the tool converts them automatically into the Telugu script.",
  },
  {
    question: "Is the Telugu typing tool free?",
    answer:
      "Yes. TypeIndian's Telugu typing tool is completely free with no sign-up, subscription, or usage limits.",
  },
  {
    question: "Can I paste English text and convert it to Telugu?",
    answer:
      "Yes. You can paste English text written phonetically and instantly convert it into Telugu script.",
  },
  {
    question: "Is this a Telugu translation tool?",
    answer:
      "No. This is a transliteration tool, not a translation tool. It converts English phonetic input into Telugu script while preserving pronunciation and meaning.",
  },
  {
    question: "How accurate is the English to Telugu transliteration?",
    answer:
      "The transliteration is highly accurate for common Telugu words and phrases. When multiple spellings are possible, TypeIndian provides suggestions to help you choose the correct one.",
  },
  {
    question: "Does TypeIndian save my Telugu text?",
    answer:
      "No. Everything you type stays in your browser. TypeIndian does not store, track, or log your text.",
  },
  {
    question: "Can I use this Telugu typing tool for professional or commercial work?",
    answer:
      "Yes. The Telugu text generated by TypeIndian can be used for personal, educational, business, and commercial purposes.",
  },
  {
    question: "Can I type long paragraphs, emails, or documents in Telugu?",
    answer:
      "Yes. TypeIndian supports writing long paragraphs, articles, emails, assignments, and documents in Telugu without restrictions.",
  },
];

export const LEARN_TELUGU_FAQ: FAQItem[] = [
  {
    question: "What script is used to write Telugu?",
    answer:
      "Telugu is written using the Telugu script, a Brahmic writing system used primarily for the Telugu language and known for its distinctive rounded letterforms.",
  },
  {
    question: "How many vowels are there in Telugu?",
    answer:
      "Telugu has 16 independent vowels. These include the basic vowels as well as vocalic vowels used mainly in Sanskrit-derived words.",
  },
  {
    question: "How many consonants are there in Telugu?",
    answer:
      "Telugu has 36 primary consonants, along with conjunct characters used in traditional writing and Sanskrit loanwords.",
  },
  {
    question: "Why do Telugu letters look rounded?",
    answer:
      "The Telugu script developed from writing on palm leaves, where rounded shapes helped prevent the leaves from tearing. This gives Telugu its distinctive curved appearance.",
  },
  {
    question: "What are Telugu vowel signs (matras)?",
    answer:
      "Telugu vowel signs are marks attached to consonants to change their vowel sound. They are an essential part of reading and writing Telugu correctly.",
  },
  {
    question: "Is Telugu written from left to right?",
    answer:
      "Yes. Telugu is written from left to right. Each consonant has an inherent vowel unless modified by a vowel sign or the virama (్).",
  },
  {
    question: "Where is Telugu spoken?",
    answer:
      "Telugu is primarily spoken in the Indian states of Andhra Pradesh and Telangana. It is also spoken by Telugu communities throughout India and around the world.",
  },
  {
    question: "Why is Telugu called the 'Italian of the East'?",
    answer:
      "Telugu is often called the 'Italian of the East' because many words end in vowel sounds, giving the language a smooth and melodic rhythm.",
  },
];