import { FAQItem } from "@/types/faq";

export const ODIA_FAQ: FAQItem[] = [
  {
    question: "What is Odia typing using English letters?",
    answer:
      "Odia typing using English letters means writing Odia words phonetically in English and converting them into the Odia script. For example, typing 'namaskar' converts to 'ନମସ୍କାର'.",
  },
  {
    question: "Which script does the Odia typing tool use?",
    answer:
      "TypeIndian's Odia typing tool uses the Odia (ଓଡ଼ିଆ) script, the standard writing system used for the Odia language.",
  },
  {
    question: "Do I need to learn the Odia keyboard layout?",
    answer:
      "No. You don't need to learn an Odia keyboard layout. Simply type Odia words using English letters and the tool converts them automatically into the Odia script.",
  },
  {
    question: "Is the Odia typing tool free?",
    answer:
      "Yes. TypeIndian's Odia typing tool is completely free with no sign-up, subscription, or usage limits.",
  },
  {
    question: "Can I paste English text and convert it to Odia?",
    answer:
      "Yes. You can paste English text written phonetically and instantly convert it into the Odia script.",
  },
  {
    question: "Is this an Odia translation tool?",
    answer:
      "No. This is a transliteration tool, not a translation tool. It converts English phonetic input into the Odia script while preserving pronunciation and meaning.",
  },
  {
    question: "How accurate is the English to Odia transliteration?",
    answer:
      "The transliteration is highly accurate for common Odia words and phrases. When multiple spellings are possible, TypeIndian provides suggestions so you can choose the correct one.",
  },
  {
    question: "Does TypeIndian save my Odia text?",
    answer:
      "No. Everything you type stays in your browser. TypeIndian does not store, track, or log your text.",
  },
  {
    question: "Can I use this Odia typing tool for professional or commercial work?",
    answer:
      "Yes. The Odia text generated by TypeIndian can be used for personal, educational, business, and commercial purposes.",
  },
  {
    question: "Can I type long paragraphs, articles, or documents in Odia?",
    answer:
      "Yes. TypeIndian supports writing long paragraphs, articles, emails, assignments, and documents in Odia without restrictions.",
  },
];

export const LEARN_ODIA_FAQ: FAQItem[] = [
  {
    question: "What script is used to write Odia?",
    answer:
      "Odia is written using the Odia script, a Brahmic writing system used primarily in the Indian state of Odisha.",
  },
  {
    question: "How many vowels are there in Odia?",
    answer:
      "Odia has 14 independent vowels. These vowels combine with consonants through vowel signs (matras) to form complete syllables.",
  },
  {
    question: "How many consonants are there in Odia?",
    answer:
      "Odia has 34 primary consonants along with additional conjunct letters used in traditional writing and Sanskrit-derived words.",
  },
  {
    question: "Why are Odia letters rounded?",
    answer:
      "The rounded appearance of the Odia script developed from writing on palm leaves, where curved strokes reduced the risk of damaging the writing surface.",
  },
  {
    question: "What are Odia vowel signs (matras)?",
    answer:
      "Odia vowel signs are marks attached to consonants to change their vowel sound. They are an essential part of reading and writing Odia correctly.",
  },
  {
    question: "Is Odia written from left to right?",
    answer:
      "Yes. Odia is written from left to right. Each consonant has an inherent vowel unless modified by a vowel sign or the virama (୍).",
  },
  {
    question: "Where is Odia spoken?",
    answer:
      "Odia is primarily spoken in Odisha and by Odia-speaking communities in neighboring states and around the world.",
  },
  {
    question: "Why is Odia a Classical Language of India?",
    answer:
      "Odia has an ancient literary tradition with inscriptions and manuscripts dating back many centuries. Its historical depth and rich body of literature led to its recognition as a Classical Language of India.",
  },
];