import { FAQItem } from "@/types/faq";

export const ASSAMESE_FAQ: FAQItem[] = [
  {
    question: "What is Assamese typing using English letters?",
    answer:
      "Assamese typing using English letters means writing Assamese words phonetically in English and converting them into the Assamese script. For example, typing 'namaskar' converts to 'নমস্কাৰ'.",
  },
  {
    question: "Which script does the Assamese typing tool use?",
    answer:
      "TypeBharat's Assamese typing tool uses the Assamese (অসমীয়া) script, also known as the Eastern Nagari script, which is the standard writing system for Assamese.",
  },
  {
    question: "Do I need to learn the Assamese keyboard layout?",
    answer:
      "No. You don't need to learn an Assamese keyboard layout. Simply type Assamese words using English letters and the tool converts them automatically into the Assamese script.",
  },
  {
    question: "Is the Assamese typing tool free?",
    answer:
      "Yes. TypeBharat's Assamese typing tool is completely free with no sign-up, subscription, or usage limits.",
  },
  {
    question: "Can I paste English text and convert it to Assamese?",
    answer:
      "Yes. You can paste English text written phonetically and instantly convert it into the Assamese script.",
  },
  {
    question: "Is this an Assamese translation tool?",
    answer:
      "No. This is a transliteration tool, not a translation tool. It converts English phonetic input into Assamese script while preserving pronunciation and meaning.",
  },
  {
    question: "How accurate is the English to Assamese transliteration?",
    answer:
      "The transliteration is highly accurate for common Assamese words and phrases. When multiple spellings are possible, TypeBharat provides suggestions so you can choose the correct one.",
  },
  {
    question: "Does TypeBharat save my Assamese text?",
    answer:
      "No. Everything you type stays in your browser. TypeBharat does not store, track, or log your text.",
  },
  {
    question: "Can I use this Assamese typing tool for professional or commercial work?",
    answer:
      "Yes. The Assamese text generated by TypeBharat can be used for personal, educational, business, and commercial purposes.",
  },
  {
    question: "Can I type long paragraphs, articles, or documents in Assamese?",
    answer:
      "Yes. TypeBharat supports writing long paragraphs, articles, emails, assignments, and documents in Assamese without restrictions.",
  },
];

export const LEARN_ASSAMESE_FAQ: FAQItem[] = [
  {
    question: "What script is used to write Assamese?",
    answer:
      "Assamese is written using the Assamese (Eastern Nagari) script. It shares the same Unicode block as the Bengali script but includes unique letters such as 'ৰ' and 'ৱ'.",
  },
  {
    question: "How many vowels are there in Assamese?",
    answer:
      "Assamese has 11 independent vowels. These vowels combine with consonants through vowel signs (matras) to form complete syllables.",
  },
  {
    question: "How many consonants are there in Assamese?",
    answer:
      "Assamese has 34 primary consonants along with additional letters and conjunct forms used in traditional writing.",
  },
  {
    question: "How is Assamese different from Bengali?",
    answer:
      "Although Assamese and Bengali share the Eastern Nagari script, Assamese has its own pronunciation, grammar, vocabulary, and unique letters such as 'ৰ' (ra) and 'ৱ' (wa).",
  },
  {
    question: "What are Assamese vowel signs (matras)?",
    answer:
      "Assamese vowel signs are marks attached to consonants to change their vowel sound. They are an essential part of reading and writing Assamese correctly.",
  },
  {
    question: "Is Assamese written from left to right?",
    answer:
      "Yes. Assamese is written from left to right. Each consonant has an inherent vowel unless modified by a vowel sign or the virama (্).",
  },
  {
    question: "Where is Assamese spoken?",
    answer:
      "Assamese is primarily spoken in the Indian state of Assam. It is also spoken by Assamese communities throughout India and abroad.",
  },
  {
    question: "Who was Srimanta Sankardeva?",
    answer:
      "Srimanta Sankardeva was a 15th-century Assamese saint, scholar, poet, playwright, and social reformer whose works played a major role in shaping Assamese literature, culture, and language.",
  },
];