import { FAQItem } from "@/types/faq";

export const MARATHI_FAQ: FAQItem[] = [
  {
    question: "What is Marathi typing using English letters?",
    answer:
      "Marathi typing using English letters means writing Marathi words phonetically in English and converting them into the Devanagari script. For example, typing 'namaskar' converts to 'नमस्कार'.",
  },
  {
    question: "Which script does the Marathi typing tool use?",
    answer:
      "TypeIndian's Marathi typing tool uses the Devanagari (देवनागरी) script, the standard writing system used for Marathi.",
  },
  {
    question: "Do I need to learn the Marathi keyboard layout?",
    answer:
      "No. You don't need to learn a Marathi keyboard layout. Simply type Marathi words using English letters and the tool converts them automatically into the Devanagari script.",
  },
  {
    question: "Is the Marathi typing tool free?",
    answer:
      "Yes. TypeIndian's Marathi typing tool is completely free with no sign-up, subscription, or usage limits.",
  },
  {
    question: "Can I paste English text and convert it to Marathi?",
    answer:
      "Yes. You can paste English text written phonetically and instantly convert it into Marathi script.",
  },
  {
    question: "Is this a Marathi translation tool?",
    answer:
      "No. This is a transliteration tool, not a translation tool. It converts English phonetic input into Marathi script while preserving pronunciation and meaning.",
  },
  {
    question: "How accurate is the English to Marathi transliteration?",
    answer:
      "The transliteration is highly accurate for common Marathi words and phrases. When multiple spellings are possible, TypeIndian provides suggestions so you can choose the correct one.",
  },
  {
    question: "Does TypeIndian save my Marathi text?",
    answer:
      "No. Everything you type stays in your browser. TypeIndian does not store, track, or log your text.",
  },
  {
    question: "Can I use this Marathi typing tool for professional or commercial work?",
    answer:
      "Yes. The Marathi text generated by TypeIndian can be used for personal, educational, business, and commercial purposes.",
  },
  {
    question: "Can I type long paragraphs, articles, or documents in Marathi?",
    answer:
      "Yes. TypeIndian supports writing long paragraphs, articles, emails, assignments, and documents in Marathi without restrictions.",
  },
];

export const LEARN_MARATHI_FAQ: FAQItem[] = [
  {
    question: "What script is used to write Marathi?",
    answer:
      "Marathi is written using the Devanagari script, which is also used for Hindi, Nepali, and Sanskrit.",
  },
  {
    question: "How many vowels are there in Marathi?",
    answer:
      "Marathi uses the Devanagari writing system and includes independent vowels along with vowel signs (matras) that combine with consonants to form syllables.",
  },
  {
    question: "How many consonants are there in Marathi?",
    answer:
      "Marathi has 34 primary consonants. It also uses additional letters and conjuncts for Sanskrit-derived and borrowed words.",
  },
  {
    question: "What makes Marathi different from Hindi?",
    answer:
      "Although Marathi and Hindi both use the Devanagari script, they are different languages with distinct grammar, pronunciation, vocabulary, and literary traditions. Marathi also makes frequent use of the consonant 'ळ', which is uncommon in Hindi.",
  },
  {
    question: "What are Marathi vowel signs (matras)?",
    answer:
      "Marathi vowel signs are marks attached to consonants to change their vowel sound. They are an essential part of reading and writing Marathi correctly.",
  },
  {
    question: "Is Marathi written from left to right?",
    answer:
      "Yes. Marathi is written from left to right. Each consonant has an inherent vowel unless modified by a vowel sign or the virama (्).",
  },
  {
    question: "Where is Marathi spoken?",
    answer:
      "Marathi is primarily spoken in the Indian state of Maharashtra. It is also spoken in Goa and by Marathi-speaking communities throughout India and around the world.",
  },
  {
    question: "Why is Marathi an important literary language?",
    answer:
      "Marathi has a rich literary tradition dating back more than 700 years. It has produced influential saints, poets, playwrights, and modern authors, making it one of India's major literary languages.",
  },
];