import { FAQItem } from "@/types/faq";

export const MALAYALAM_FAQ: FAQItem[] = [
  {
    question: "What is Malayalam typing using English letters?",
    answer:
      "Malayalam typing using English letters means writing Malayalam words phonetically in English and converting them into the Malayalam script. For example, typing 'namaskaram' converts to 'നമസ്കാരം'.",
  },
  {
    question: "Which script does the Malayalam typing tool use?",
    answer:
      "TypeIndian's Malayalam typing tool uses the Malayalam (മലയാളം) script, the standard writing system used for the Malayalam language.",
  },
  {
    question: "Do I need to learn the Malayalam keyboard layout?",
    answer:
      "No. You don't need to learn a Malayalam keyboard layout. Simply type Malayalam words using English letters and the tool converts them automatically into the Malayalam script.",
  },
  {
    question: "Is the Malayalam typing tool free?",
    answer:
      "Yes. TypeIndian's Malayalam typing tool is completely free with no sign-up, subscription, or usage limits.",
  },
  {
    question: "Can I paste English text and convert it to Malayalam?",
    answer:
      "Yes. You can paste English text written phonetically and instantly convert it into Malayalam script.",
  },
  {
    question: "Is this a Malayalam translation tool?",
    answer:
      "No. This is a transliteration tool, not a translation tool. It converts English phonetic input into Malayalam script while preserving pronunciation and meaning.",
  },
  {
    question: "How accurate is the English to Malayalam transliteration?",
    answer:
      "The transliteration is highly accurate for common Malayalam words and phrases. When multiple spellings are possible, TypeIndian provides suggestions so you can choose the correct one.",
  },
  {
    question: "Does TypeIndian save my Malayalam text?",
    answer:
      "No. Everything you type stays in your browser. TypeIndian does not store, track, or log your text.",
  },
  {
    question: "Can I use this Malayalam typing tool for professional or commercial work?",
    answer:
      "Yes. The Malayalam text generated by TypeIndian can be used for personal, educational, business, and commercial purposes.",
  },
  {
    question: "Can I type long paragraphs, articles, or documents in Malayalam?",
    answer:
      "Yes. TypeIndian supports writing long paragraphs, articles, emails, assignments, and documents in Malayalam without restrictions.",
  },
];

export const LEARN_MALAYALAM_FAQ: FAQItem[] = [
  {
    question: "What script is used to write Malayalam?",
    answer:
      "Malayalam is written using the Malayalam script, a Brahmic writing system primarily used in the Indian state of Kerala.",
  },
  {
    question: "How many vowels are there in Malayalam?",
    answer:
      "Malayalam has 16 independent vowels. These vowels combine with consonants through vowel signs (matras) to form complete syllables.",
  },
  {
    question: "How many consonants are there in Malayalam?",
    answer:
      "Malayalam has 36 primary consonants along with additional conjunct letters and traditional characters used in literary and Sanskrit-derived words.",
  },
  {
    question: "Why does Malayalam have rounded letters?",
    answer:
      "Malayalam's rounded letterforms developed from centuries of writing on palm leaves, where curved strokes helped avoid tearing the writing surface.",
  },
  {
    question: "What is the letter 'ഴ' in Malayalam?",
    answer:
      "The letter 'ഴ' (ഴ) represents a unique retroflex approximant sound that is one of the most distinctive features of Malayalam pronunciation and has no exact equivalent in English.",
  },
  {
    question: "Is Malayalam written from left to right?",
    answer:
      "Yes. Malayalam is written from left to right. Each consonant has an inherent vowel unless modified by a vowel sign or the virama (്).",
  },
  {
    question: "Where is Malayalam spoken?",
    answer:
      "Malayalam is primarily spoken in Kerala, Lakshadweep, and the Mahé region of Puducherry. It is also spoken by large Malayali communities around the world.",
  },
  {
    question: "Why is Malayalam a Classical Language of India?",
    answer:
      "Malayalam has a rich literary tradition spanning many centuries, with extensive poetry, prose, and scholarly works. Its historical significance and literary heritage led to its recognition as a Classical Language of India.",
  },
];