import { FAQItem } from "@/types/faq";

export const TAMIL_FAQ: FAQItem[] = [
  {
    question: "What is Tamil typing using English letters?",
    answer:
      "Tamil typing using English letters means writing Tamil words phonetically in English and converting them into the Tamil script. For example, typing 'vanakkam' converts to 'வணக்கம்'.",
  },
  {
    question: "Which script does the Tamil typing tool use?",
    answer:
      "TypeBharat’s Tamil typing tool uses the Tamil (தமிழ்) script, the standard writing system used for the Tamil language.",
  },
  {
    question: "Do I need to learn the Tamil keyboard layout?",
    answer:
      "No. You don't need to learn a Tamil keyboard layout. Simply type Tamil words using English letters and the tool converts them automatically into the Tamil script.",
  },
  {
    question: "Is the Tamil typing tool free?",
    answer:
      "Yes. TypeBharat’s Tamil typing tool is completely free to use with no sign-up, subscription, or usage limits.",
  },
  {
    question: "Can I paste English text and convert it to Tamil?",
    answer:
      "Yes. You can paste English text written phonetically and instantly convert it into the Tamil script.",
  },
  {
    question: "Is this a Tamil translation tool?",
    answer:
      "No. This is a transliteration tool, not a translation tool. It converts English phonetic input into Tamil script while preserving the pronunciation and meaning.",
  },
  {
    question: "How accurate is the English to Tamil transliteration?",
    answer:
      "The transliteration is highly accurate for common Tamil words and phrases. When multiple spellings are possible, TypeBharat provides suggestions so you can choose the correct one.",
  },
  {
    question: "Does TypeBharat save my Tamil text?",
    answer:
      "No. Everything you type stays in your browser. TypeBharat does not store, track, or log your text.",
  },
  {
    question: "Can I use this Tamil typing tool for professional or commercial work?",
    answer:
      "Yes. The Tamil text generated by TypeBharat can be used for personal, educational, business, and commercial purposes.",
  },
  {
    question: "Can I type long paragraphs, lyrics, or documents in Tamil?",
    answer:
      "Yes. TypeBharat supports writing long paragraphs, articles, lyrics, assignments, emails, and documents without restrictions.",
  },
];

export const LEARN_TAMIL_FAQ: FAQItem[] = [
  {
    question: "What is the script used to write Tamil?",
    answer:
      "Tamil is written using the Tamil script, one of the oldest continuously used writing systems in the world. It is primarily used to write the Tamil language.",
  },
  {
    question: "How many vowels are there in Tamil?",
    answer:
      "Tamil has 12 independent vowels (உயிரெழுத்துகள்). These vowels represent the basic vowel sounds used in the language.",
  },
  {
    question: "How many consonants are there in Tamil?",
    answer:
      "Tamil has 18 native consonants (மெய்யெழுத்துகள்). In addition, Grantha letters are used to represent sounds found in Sanskrit and some foreign words.",
  },
  {
    question: "What is the special letter 'ஃ' in Tamil?",
    answer:
      "The character 'ஃ', called Aytham (ஆய்த எழுத்து), is a unique letter in the Tamil script. It is used in classical Tamil and in certain modern transliterations and borrowed words.",
  },
  {
    question: "What are Tamil vowel signs (matras)?",
    answer:
      "Tamil vowel signs are marks added to consonants to change their vowel sound. These dependent vowel signs combine with consonants to form complete syllables in written Tamil.",
  },
  {
    question: "Is Tamil written from left to right?",
    answer:
      "Yes. Tamil is written from left to right and uses an abugida writing system, where each consonant has an inherent vowel unless modified by a vowel sign or the Pulli (்).",
  },
  {
    question: "Where is Tamil spoken?",
    answer:
      "Tamil is primarily spoken in the Indian state of Tamil Nadu and the Union Territory of Puducherry. It is also an official language of Sri Lanka and Singapore and is spoken by millions of Tamil communities around the world.",
  },
  {
    question: "Why is Tamil considered one of the world's oldest languages?",
    answer:
      "Tamil has a recorded literary history spanning more than two thousand years. It is recognized as a Classical Language of India and continues to be widely spoken and written today.",
  },
];