import { FAQItem } from "@/types/faq";

export const BENGALI_FAQ: FAQItem[] = [
  {
    question: "What is Bengali typing using English letters?",
    answer:
      "Bengali typing using English letters means writing Bengali words phonetically in English and converting them into the Bengali (Bangla) script. For example, typing 'ami bhalo achi' converts to 'আমি ভালো আছি'.",
  },
  {
    question: "Which script does the Bengali typing tool use?",
    answer:
      "TypeIndian's Bengali typing tool uses the Bengali (বাংলা) script, the standard writing system used for Bengali in India and Bangladesh.",
  },
  {
    question: "Do I need to learn the Bengali keyboard layout?",
    answer:
      "No. You don't need to learn a Bengali keyboard layout. Simply type Bengali words using English letters and the tool converts them automatically into the Bengali script.",
  },
  {
    question: "Is the Bengali typing tool free?",
    answer:
      "Yes. TypeIndian's Bengali typing tool is completely free to use with no sign-up, subscription, or usage limits.",
  },
  {
    question: "Can I paste English text and convert it to Bengali?",
    answer:
      "Yes. You can paste English text written phonetically and instantly convert it into Bengali script.",
  },
  {
    question: "Is this a Bengali translation tool?",
    answer:
      "No. This is a transliteration tool, not a translation tool. It converts English phonetic input into Bengali script while preserving pronunciation and meaning.",
  },
  {
    question: "How accurate is the English to Bengali transliteration?",
    answer:
      "The transliteration is highly accurate for common Bengali words and phrases. When multiple spellings are possible, TypeIndian provides suggestions so you can choose the correct form.",
  },
  {
    question: "Does TypeIndian save my Bengali text?",
    answer:
      "No. Everything you type stays in your browser. TypeIndian does not store, track, or log your text.",
  },
  {
    question: "Can I use this Bengali typing tool for professional or commercial work?",
    answer:
      "Yes. The Bengali text generated by TypeIndian can be used for personal, educational, business, and commercial purposes.",
  },
  {
    question: "Can I type long paragraphs, articles, or documents in Bengali?",
    answer:
      "Yes. TypeIndian supports writing long paragraphs, articles, emails, assignments, and documents in Bengali without restrictions.",
  },
];

export const LEARN_BENGALI_FAQ: FAQItem[] = [
  {
    question: "What script is used to write Bengali?",
    answer:
      "Bengali is written using the Bengali (Bangla) script, a Brahmic writing system used for Bengali, Assamese, and several other regional languages.",
  },
  {
    question: "How many vowels are there in Bengali?",
    answer:
      "Bengali has 11 independent vowels. These vowels combine with consonants through vowel signs (matras) to form syllables.",
  },
  {
    question: "How many consonants are there in Bengali?",
    answer:
      "Bengali has 39 traditional consonants. Modern Bengali commonly uses 32 primary consonants along with additional letters and conjunct forms.",
  },
  {
    question: "What are Bengali conjunct letters (যুক্তাক্ষর)?",
    answer:
      "Conjunct letters are combinations of two or more consonants written together as a single unit. They are widely used in Bengali writing, especially in Sanskrit-derived words.",
  },
  {
    question: "What are Bengali vowel signs (matras)?",
    answer:
      "Bengali vowel signs are marks attached to consonants to change their vowel sound. They are an essential part of reading and writing Bengali correctly.",
  },
  {
    question: "Is Bengali written from left to right?",
    answer:
      "Yes. Bengali is written from left to right. Each consonant has an inherent vowel unless modified by a vowel sign or the Hasanta (্).",
  },
  {
    question: "Where is Bengali spoken?",
    answer:
      "Bengali is spoken primarily in the Indian states of West Bengal, Tripura, and parts of Assam, and it is the national language of Bangladesh. It is spoken by more than 250 million people worldwide.",
  },
  {
    question: "Why is Bengali an important literary language?",
    answer:
      "Bengali has one of the richest literary traditions in South Asia. It is the language of Nobel laureate Rabindranath Tagore and has a long history of poetry, novels, music, and philosophy.",
  },
];